export enum Country {
  "NL" = "NL",
  "DE" = "DE",
  "DK" = "DK",
  "NO" = "NO",
  "SE" = "SE",
  "BE" = "BE",
  "FI" = "FI",
  "US" = "US",
  "SA" = "SA",
  "IR" = "IR",
  "EE" = "EE",
  "GB" = "GB",
  "IE" = "IE",
  "MT" = "MT",
  "AT" = "AT",
  "CH" = "CH",
  "IL" = "IL",
  "ES" = "ES",
  "IN" = "IN",
  "LK" = "LK",
  "AZ" = "AZ",
  "TR" = "TR",
  "IT" = "IT",
  "KZ" = "KZ",
  "UZ" = "UZ",
  "XK" = "XK",
  "AL" = "AL",
  "PT" = "PT",
  "FR" = "FR",
  "HR" = "HR",
  "BA" = "BA",
  "AM" = "AM",
  "LU" = "LU",
  "GR" = "GR",
  "RO" = "RO",
  "LV" = "LV",
  "MD" = "MD",
  "IS" = "IS",
  "PL" = "PL",
  "CZ" = "CZ",
  "SK" = "SK",
  "BG" = "BG",
  "SI" = "SI",
  "ME" = "ME",
  "MK" = "MK",
  "GE" = "GE",
  "RU" = "RU",
  "HU" = "HU",
  "KR" = "KR",
  "KP" = "KP",
  "JP" = "JP",
  "CN" = "CN",
  "BY" = "BY",
  "LT" = "LT",
  "UA" = "UA",
  "RS" = "RS",
  "VN" = "VN",
}

export enum Gender {
  "M" = "M",
  "F" = "F",
  "?F" = "?F",
  "?" = "?",
  "?M" = "?M",
  "1F" = "1F",
  "1M" = "1M",
}

export enum Nationality {
  "Ethiopian" = "Ethiopian",
  "Honduran" = "Honduran",
  "Malaysian" = "Malaysian",
  "Chilean" = "Chilean",
  "Portuguese" = "Portuguese",
  "Algerian" = "Algerian",
  "Brazilian" = "Brazilian",
  "Venezuelan" = "Venezuelan",
  "Ukrainian" = "Ukrainian",
  "Nicaraguan" = "Nicaraguan",
  "Moroccan" = "Moroccan",
  "Finnish" = "Finnish",
  "Mexican" = "Mexican",
  "Palestinian" = "Palestinian",
  "Nepalese" = "Nepalese",
  "Peruvian" = "Peruvian",
  "Dutch" = "Dutch",
  "Arabic" = "Arabic",
  "Irish" = "Irish",
  "Spanish" = "Spanish",
  "French" = "French",
  "German" = "German",
  "English" = "English",
  "Korean" = "Korean",
  "Indian" = "Indian",
  "Vietnamese" = "Vietnamese",
  "Scottish" = "Scottish",
  "Japanese" = "Japanese",
  "Polish" = "Polish",
  "Greek" = "Greek",
  "Czech" = "Czech",
  "Italian" = "Italian",
  "Russian" = "Russian",
  "Chinese" = "Chinese",
}

export interface Firstname {
  name: string;
  gender: Gender;
  countries: Country[];
  nationalities: Nationality[];
}

export interface Surnames {
  surname: string;
  nationality: Nationality;
}
